#### configuration for the verification run
general:

  # define which of the 5 steps to run; each step can be run independently, 
  # assuming data from previous steps (from previous runs) are available for use
  steps:
    fetch_fcst_data: true
    fetch_obs_data: true
    pair_data: true
    compute_metrics: true
    plot_metrics: true

  # user-specified name for the set of locations to carry out verification for
  # this name is used to create a folder in 'data_dir_root' (in 'file_paths' section) to store all the datasets and outputs
  # see function 'data_paths' in ngen-verf/src/ngen/verf/settings.py to see how the overall data directory structure is defined
  location_set_name: calib_basin_group1

  # [optional] list of usgs gage IDs or NWM links IDs; if blank, a static location_list_file containing 100 gages will be used
  location_list: ["01123000", "01010000"]

  # [optional] must be specified if location_list is not blank; currently supported options: usgs_gage, nwm30_link
  location_type: usgs_gage

  variable_name: streamflow # currently only 'streamflow' is supported
  nwm_configuration: short_range   # Currently, only short_range, short_range_alaska, short_range_hawaii, and short_range_puertorico are supported

  # user-specified name of datasets (used for creating sub-folders for datasets and plots)
  # must be a list of one or more strings
  dataset_name: [v3_sep, v3_oct]

  # list of NWM versions; must have the same length as 'dataset_name'. Currently only option is "nwm30"
  nwm_version: [nwm30, nwm30]

  # list of start/end dates for forecast verification period; list must have the same length as 'dataset_name'
  # date ranges specified must be applicable to the corresponding NWM archive in Google Cloud 
  forecast_start_date: ['2024-09-01', '2024-10-01']
  forecast_end_date: ['2024-09-30', '2024-10-30']

#### configurations for various file paths
# sample files can be obtained from repo at ngen-verf/sample_files/gage_files
file_paths:

  # root directory to store the downloaded NWM forecast and flow observation data
  data_dir_root: /home/yuqiong.liu/work/data/ngen-verf

  # [optional] but either location_list (in 'general' section) or location_list_file must be specifed
  # tab or comma delimited csv file, and must contain either a "gage" or 
  # a "link" column (e.g., nwm30_link) specifying the locations to conduct verification for 
  # sample files for different domains are available at ngen-verf/sample_files/gage_files
  # below is a sample file with 100 calibrated USGS gages for CONUS domain
  location_list_file: /home/yuqiong.liu/work/Gitlab/ngen-verf/sample_files/gage_files/usgs_gages_link_CONUS_calib100.csv 

  # parquet files containing the crosswalk between NWM feature_id and usgs gage id
  # note a crosswalk file should be provided for each NWM version listed in 'general/nwm_version'
  # see utils/create_crosswalk.py on how the sample crosswalk parquet was created
  # sample file usgs_nwm30_crosswalk_all_domains.parquet includes 8866 gages
  crosswalk_file:
    nwm30: 
      /home/yuqiong.liu/work/Gitlab/ngen-verf/sample_files/gage_files/usgs_nwm30_crosswalk_all_domains.parquet
    #nwm40:

  # meta data for USGS gages (sample file gages_metadata_all_domains.csv includes 8660 USGS gages)
  gage_meta_file: /home/yuqiong.liu/work/Gitlab/ngen-verf/sample_files/gage_files/gages_metadata_all_domains.csv

  # geometry (point lat/lon) for USGS gages; see utils/create_geometry.py on how the sample geometry parquet was created
  # sample file usgs_point_geometry_CONUS.parquet includes 8186 USGS gages
  geometry_file: /home/yuqiong.liu/work/Gitlab/ngen-verf/sample_files/gage_files/usgs_point_geometry_all_domains.parquet

#### configurations for retrieving NWM forecast data (typically no need to change)
nwm_forecast:
  fetch_fcst: [true, true]  # whether to fetch the forecast data for each dataset listed in ['general']['dataset_name']
  output_type: channel_rt
  t_minus: [0, 1, 2]  # Only used if an assimilation run is selected
  data_source: GCS    # Specifies the remote location from which to fetch the data ("GCS", "NOMADS", "DSTOR")
  kerchunk_method: local  # When data_source = "GCS", specifies the preference in creating Kerchunk reference json files.
                          # "local" - always create new json files from netcdf files in GCS and save locally, if they do not already exist
                          # "remote" - read the CIROH pre-generated jsons from s3, ignoring any that are unavailable
                          # "auto" - read the CIROH pre-generated jsons from s3, and create any that are unavailable, storing locally

  process_by_z_hour: true  # If True, NWM files will be processed by z-hour per day. If False, files will be
                         # processed in chunks (defined by STEPSIZE). This can help if you want to read many reaches
                         # at once (all ~2.7 million for medium range for example).

  stepsize: 100  # Only used if PROCESS_BY_Z_HOUR = False. Controls how many files are processed in memory at once
                # Higher values can increase performance at the expense on memory  (default value: 100)

  ignore_missing_file: false  # If True, the missing file(s) will be skipped and the process will resume
                           # If False, TEEHR will fail if a missing NWM file is encountered

  overwrite_output: false  # If True, existing output files will be overwritten; if False, existing files are retained

  memory_per_worker_gb: 3  # configurable memory (in GB) assigned to each worker

#### configurations for retrieving streamflow observation data (currently only usgs is supported)
#### typically no need to change selections in this section
flow_observation:
  usgs: # flow obs retrieved will be stored at [data_dir_root]/[location_set_name]/usgs
    chunk_by: day   # data are saved in parquet files by day/month/year
    overwrite_output: false  # If True, existing output files will be overwritten; if False, existing files are retained
    memory_per_worker_gb: 3  # configurable memory (in GB) assigned to each worker

#### paired data generation
pair_data:

  # whether to overwrite existing joined parquet files
  overwrite: true

  # break large location list into smaller groups (for pair_data and cacl_metrics steps) to avoid potential memory issues and to speed up processing
  group_size: 200

#### configuration for metrics calculation
metrics:

  # whether to overwrite existing metric files
  overwrite: true

  # library to be used for metric calculation; currently supported options: teehr, ngen.eval
  # see the lists of supported metrics toward the end of sample config.yaml file (also ngen-verf/src/ngen/verf/settings.py)
  library: ngen.eval

  # list of metrics to be calculated 
  # if set to 'all', all available metrics will be calculated
  # [caution] some metrics available in ngen.eval (e.g., event-based metrics) may be time consuming to compute
  #metric_subset: [KGE, NSE, CORR, NNSE]
  metric_subset: 'all'

  # list of metrics to be excluded from calculation (leave blank if no need to exclude any metrics)
  # here the event-based metrics are excluded because they are time consuming to run
  metric_exclude: [PKBIAS, PKTE, EVBIAS, FBIAS]

  # non-exceedance probability threshold of streamflow to be used for categorical metrics in ngen.eval
  flow_threshold_categorical: 0.9

  # non-exceedance probability threshold of streamflow to be used for event-based metrics in ngen.eval
  flow_threshold_event: 0.9

  # list of lead times (in hours) for which metrics should be calculated for
  # the lead times can be integers (e.g., 1,2), or an interval (e.g., 1-3), or 'all'
  # if set to 'all', all raw lead times (i.e., 1, 2, ..., 18 in the case of short-range forecasts) will be calculated
  #lead_times: [1,3,5,'1-3','1-5','4-6','6-10']
  lead_times: [all, 1-5, 6-10, 11-18]

#### configuration for plots
# For each type of plots (histogram, boxplot, spatial map), 
#   1) 'metric_subset' must be a subset of metrics defined for calculation (i.e., 'metric_subset' defined in Section 'metrics')
#   2) 'lead_times' must be a subset of lead times defined for metrics calculation (i.e., 'lead_times' defined in Section 'metrics')
plots:
  histogram:

    # whether to create histogram plots
    plot: true

    # list of metrics to create histogram plots for
    metric_subset: [KGE, NSE, CORR, NNSE]

    # for each metric, define list of bin edges for generating the histogram plot
    # For 'KGE','NSE','CORR' and 'NNSE', default bins (see settings.py) will be used if not defined. 
    # For other metrics, the data will be cut into 8 equal-width bins if bin edges are not provided 
    binning:
      KGE: [-inf, -1, -0.5, 0, 0.2, 0.4, 0.6, 0.8, 1.0]
      NSE: [-inf, -1, -0.5, 0, 0.2, 0.4, 0.6, 0.8, 1.0]
      NNSE: [0, 0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0]
      CORR: [-1, -0.5, 0, 0.2, 0.4, 0.6, 0.8, 1.0]

    # list of lead times (in hours) to create histograms for
    lead_times: [1, 3, 5, 10, 15, 18, 1-5, 6-10, 11-18]

    # define a string that gets added to the filename of histogram plots to differentiate between plots 
    # of different lead time groups or different binning scenarios, to avoid overwriting the existing plots. 
    # Leave it blank if overwriting is desired
    tag:

  boxplot: # the same comments for histogram apply here (except for binning)
    plot: true
    metric_subset: [KGE, NSE, CORR, NNSE]

    # Define an appropriate range (min/max) for each metric to scale the boxplot.
    # Default ranges (see settings.py) will be applied for 'KGE', 'NSE', 'CORR', and 'NNSE' if not specified.
    # For other metrics, if a range is not defined, values will remain unscaled, 
    #    which may result in improperly displayed statistics due to outliers.    
    scaling:
      KGE: [-0.5, 1]
      NSE: [-0.5, 1]
      CORR: [-0.5, 1]
      NNSE: [0, 1]
      RSR: [0, 20]
      MAE: [0, 5]
      RMSE: [0, 20]
      PBIAS: [-100, 300]

    lead_times: [1, 3, 5, 10, 15, 18, 1-5, 6-10, 11-18]
    show_outliers: false
    tag:

  spatial_map:
    plot: true

    # list of metrics to create spatial maps for
    metric_subset: [KGE, NSE, CORR, NNSE]

    # Define an appropriate range (min/max) for each metric to scale the values for the spatial map
    scaling:
      KGE: [-0.5, 1]
      NSE: [-0.5, 1]
      CORR: [-0.5, 1]
      NNSE: [0, 1]
      RSR: [0, 20]
      MAE: [0, 20]
      RMSE: [0, 20]
      PBIAS: [-100, 300]

    lead_times: [1, 3, 5, 10, 15, 18, 1-5, 6-10, 11-18]

    # define a string that gets added to the filename of spatial map plots to avoid overwriting the existing ones (if any)
    tag:

############### DONE WITH CONFIGURATIONS #######################                  
#--------- List of currently supported metrics for teehr and ngen.eval -----------
# both short and long names of the metrics are accepted
#
### supported metrics for teehr
    # 'n_obs': 'primary_count', 
    # 'n_mod': 'secondary_count',
    # 'min_obs': 'primary_minimum', 
    # 'min_mod': 'secondary_minimum', 
    # 'max_obs': 'primary_maximum',
    # 'max_mod': 'secondary_maximum', 
    # 'mean_obs': 'primary_average', 
    # 'mean_mod': 'secondary_average',
    # 'sum_obs': 'primary_sum', 
    # 'sum_mod': 'secondary_sum', 
    # 'var_obs': 'primary_variance',
    # 'var_mod': 'secondary_variance', 
    # 'max_delta': 'max_value_delta', 
    # 'NSE': 'nash_sutcliffe_efficiency',
    # 'NNSE': 'nash_sutcliffe_efficiency_normalized', 
    # 'KGE': 'kling_gupta_efficiency',
    # 'KGE1': 'kling_gupta_efficiency_mod1', 
    # 'KGE2': 'kling_gupta_efficiency_mod2',
    # 'ME': 'mean_error', 
    # 'MAE': 'mean_absolute_error', 
    # 'MSE': 'mean_squared_error',
    # 'RMSE': 'root_mean_squared_error',
    # 'pt_obs': 'primary_max_value_time',
    # 'pt_mod': 'secondary_max_value_time', 
    # 'pt_err': 'max_value_timedelta',
    # 'RBIAS': 'relative_bias',
    # 'MBAIS': 'multiplicative_bias', 
    # 'RMAE': 'mean_absolute_relative_error',
    # 'CORR': 'pearson_correlation',
    # 'sCORR': 'spearman_correlation',    
    # 'R2': 'r_squared', 
    # 'aprBIAS': 'annual_peak_relative_bias',


##### supported metrics for ngen.eval
    # 'CORR': 'pearson correlation',
    # 'NSE': 'nash_sutcliffe_efficiency',
    # 'NNSE': 'nash_sutcliffe_efficiency_normalized', 
    # 'NSElog': "logrithmic nash_sutcliffe_efficiency",
    # 'NSEwt': 'weighted NSE and NSElog',
    # 'KGE': 'kling_gupta_efficiency',
    # 'MAE': 'mean_absolute_error', 
    # 'RMSE': 'root_mean_squared_error',
    # 'PBIAS': 'percent_bias',
    # 'RSR': 'RMSE_observation_std_ratio',
    # 'HSEG_FDC': 'pbias_high_flow_FDC',
    # 'MSEG_FDC': 'pbias_medium_flow_FDC',
    # 'LSEG_FDC': 'pbias_low_flow_FDC',
    # 'POD': 'probability_of_detection',
    # 'FAR': 'false_alarm_ratio',
    # 'CSI': 'critical_success_index',
    # 'FBIAS': 'frequency_bias',
    # 'PKBIAS': 'percent_peak_flow_bias',
    # 'PKTE': 'peak_timing_error',
    # 'EVBIAS': 'event_volume_bias',


