# Generated by Django 5.2.12 on 2026-04-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0066_forecastconfiguration_supports_hindcast_hindcastrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrun',
            name='hindcast_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_runs', to='calibration.hindcastrun'),
        ),
        migrations.AlterField(
            model_name='verificationrun',
            name='forecast_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_runs', to='calibration.forecastrun'),
        ),
        migrations.AddIndex(
            model_name='verificationrun',
            index=models.Index(fields=['hindcast_run'], name='idx_verif_hindcast_run'),
        ),
        migrations.AddConstraint(
            model_name='verificationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('forecast_run__isnull', False), ('hindcast_run__isnull', True)), models.Q(('forecast_run__isnull', True), ('hindcast_run__isnull', False)), _connector='OR'), name='verif_exactly_one_parent_run'),
        ),
    ]
