# Generated by Django 5.2.13 on 2026-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0066_forecastconfiguration_supports_hindcast_hindcastrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
