# Generated by Django 5.2.13 on 2026-04-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0067_verificationrun_hindcast_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hindcastrun',
            name='created_new_cold_start',
            field=models.BooleanField(default=False),
        ),
    ]
